CREATE TABLE tv (
	id BIGINT(50) PRIMARY KEY AUTO_INCREMENT,
	local_tv VARCHAR(50) NOT NULL,
	modelo VARCHAR(15) NOT NULL,
	marca VARCHAR(15) NOT NULL,
	chave VARCHAR(20) NOT NULL,
	tv_disponivel VARCHAR(3) NOT NULL,
	tv_online BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE tv ADD UNIQUE (chave);
