CREATE TABLE midia ( 
	id BIGINT(50) PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(50) NOT NULL,
	palavra_chave VARCHAR(50) NOT NULL,
	data_criacao DATE NOT NULL,
	tipo_midia VARCHAR(10) NOT NULL,
	disponibilidade VARCHAR(10) NOT NULL,
	link VARCHAR(80) NULL,
	duracao INTEGER NULL
 )ENGINE=InnoDB DEFAULT CHARSET=utf8;