CREATE TABLE chave(
	id BIGINT(50) PRIMARY KEY AUTO_INCREMENT,
	chave VARCHAR(100) NOT NULL,
    midia_id BIGINT(50) NOT NULL,
	FOREIGN KEY (midia_id) REFERENCES midia(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;